# Package

version = "0.1.0"
author = "Jacek Sieka"
description = "WinMD tools and API generator"
license = "MIT"
srcDir = "src"
installExt = @["nim"]
bin = @["winmd2nim", "winmd2yaml"]

# Dependencies

requires "nim >= 2.2.10"
requires "checksums" # SHA-1, for the IIDs of WinRT generic instantiations

# Tasks

import strutils, sequtils, pathnorm, os

# the helpers build and run straight from tools/ (no src/ shims needed);
# `exec` raises on a non-zero exit, so a failed helper fails the task
task checkabi, "ABI-check the generated bindings against the mingw headers":
  const winmd = normalizePath("windows-rs/crates/libs/default/Windows.Win32.winmd")
  const rdl = normalizePath("windows-rs/metadata")
  const outDir = "_exper/gen_hdr"
  const test = "_exper/checkabi.nim"
  const exe = "_exper/checkabi.exe"

  exec("nimble build winmd2nim -d:release")

  rmDir(outDir)
  mkDir(outDir)

  exec("./winmd2nim --headers " & winmd & " " & outDir & " " & rdl & "")

  const flags = when defined(linux): " -d:mingw" else: ""

  selfExec(
    "c -d:checkAbi --verbosity:0 --hints:off --path:_exper -o:" & exe & "" & flags &
      " tests/checkabi"
  )

  when defined(linux):
    # 5. run it under wine
    exec("wine '" & exe & "'")
  else:
    exec(exe)

task fullcheck, "Full-surface compile: import all generated modules":
  const hdrDir = "_exper/gen_hdr"
  const agg = "_exper/gen_hdr/zz_temp_agg.nim"

  # the headers are generated by the checkabi task
  if not dirExists(hdrDir):
    exec("nimble checkabi")

  let names = listFiles(hdrDir)
    .filterIt(it.endsWith(".nim"))
    .mapIt(splitFile(it).name)
    .filterIt(it != "zz_temp_agg")

  writeFile(
    agg,
    "# temp aggregate (full-surface compile check)\n" &
      names.mapIt("import " & it & "\n").join(""),
  )

  const flags = when defined(linux): " -d:mingw" else: ""

  selfExec("c --verbosity:0 --hints:off -o:full_check.exe" & flags & " " & agg)

task win32abi, "generate the win32 abi into ../nim-win32-abi":
  exec "nim c -r --verbosity:0 --hints:off -d:release -o:win32abi tools/win32abi.nim"

task test, "Run tests":
  # listFiles uses the platform's path separator (`tests\test_x.nim` on Windows)
  for t in listFiles("tests/").filterIt(
    it.extractFilename.startsWith("test") and it.endsWith(".nim")
  ):
    echo "testing ", t
    exec "nim c -d:release -r --hints:off --verbosity:0 " & t
