# render.nim — the Nim source of the WinRT modules, from the plan alone.

import std/[algorithm, options, sequtils, strformat, strutils]
import ../[guid, generator]
import ./plan
{.push warning[UnusedImport]: off.}
from ./winrtbase import nil # so the compiler checks it
{.pop.}

const baseModule = staticRead("winrtbase.nim").replace("\r\n", "\n")
  ## winrtbase, written out as is.

func lines(xs: openArray[string]): string =
  ## `xs`, each followed by a newline.
  xs.mapIt(it & "\n").join

func paragraph(xs: seq[string]): string =
  ## `xs` after a blank line; "" when empty.
  if xs.len > 0:
    lines(@[""] & xs)
  else:
    ""

func section(keyword: string, xs: seq[string]): string =
  ## A `type` or `const` section; "" when empty (an empty one does not parse).
  if xs.len > 0:
    paragraph(@[keyword] & xs)
  else:
    ""

func header(name: string, about = ""): string =
  ## A module's doc comment.
  let first =
    fmt"## generated by winmd2nim from WinRT metadata — {name} (do not edit)"
  if about.len > 0:
    first & "\n## " & about
  else:
    first

func spell(t: AbiType): string =
  ## `t` in Nim: `ptr IVector[HSTRING]`.
  case t.kind
  of akVoid:
    "void"
  of akNamed:
    t.name
  of akPointer:
    if t.target.kind == akVoid:
      "pointer"
    else:
      "ptr " & spell(t.target)
  of akInstantiation:
    let args = t.args.map(spell).join(", ")
    fmt"{t.definition}[{args}]"
  of akArray:
    fmt"array[{t.count}, {spell(t.element)}]"

func hasVtable(d: Declaration): bool =
  ## An interface or delegate.
  d.kind in {dkInterface, dkDelegate}

func isParameterised(d: Declaration): bool =
  ## `IVector[T]`
  d.hasVtable and d.genericParameters.len > 0

func generics(d: Declaration): string =
  ## `[K, V]`, or "".
  if d.genericParameters.len > 0:
    let list = d.genericParameters.join(", ")
    fmt"[{list}]"
  else:
    ""

# ---------------------------------------------------------------------------
# declarations
# ---------------------------------------------------------------------------

func slotType(s: VtableSlot): string =
  ## A slot's proc type, or `pointer` when it cannot be spelled.
  if s.parameters.isNone:
    return "pointer # signature not mapped"
  let list = s.parameters.get.mapIt(fmt"{it.name}: {spell(it.ty)}").join(", ")
  fmt"proc({list}): HRESULT {{.stdcall.}}"

func typeDeclaration(d: Declaration): seq[string] =
  ## The declaration of `d` in a type section.
  case d.kind
  of dkEnum:
    @[fmt"  {d.name}* = distinct {spell(d.underlying)}"]
  of dkStruct:
    @[fmt"  {d.name}* {{.mdtype.}} = object"] &
      d.fields.mapIt(fmt"    {it.name}*: {spell(it.ty)}")
  of dkInterface, dkDelegate:
    @[
      fmt"  {d.name}*{generics(d)} {{.mdinterface.}} = object",
      fmt"    lpVtbl*: ptr {d.vtableName}{generics(d)}",
    ]
  of dkClass:
    if d.defaultInterface.isSome:
      @[fmt"  {d.name}* {{.mdalias.}} = {spell(d.defaultInterface.get)}"]
    else: # a static class
      @[fmt"  {d.name}* {{.mdinterface.}} = object", "    lpVtbl*: pointer"]

func vtableDeclaration(d: Declaration): seq[string] =
  ## The vtable of interface or delegate `d`.
  let parent = if d.kind == dkDelegate: "IUnknownVtbl" else: "IInspectableVtbl"
  @[fmt"  {d.vtableName}*{generics(d)} {{.mdvtbl.}} = object of {parent}"] &
    d.slots.mapIt(fmt"    {it.name}*: {slotType(it)}")

func constDeclarations(d: Declaration): seq[string] =
  ## The consts of `d`: an IID, a class name, or enum members.
  case d.kind
  of dkInterface, dkDelegate:
    @[fmt"  {d.iidName}*: GUID = {nimLiteral(d.guid)}"]
  of dkClass:
    @[fmt"  {d.classNameConst}*: string = {escape(d.className)}"]
  of dkEnum:
    d.members.mapIt(fmt"  {it.name}*: {d.name} = {d.name}({it.value})")
  of dkStruct:
    @[]

func enumFuncs(d: Declaration): seq[string] =
  ## The operations enum `d` borrows from its integer.
  if d.kind != dkEnum:
    return
  let t = d.name
  result = @[
    "",
    fmt"func `==`*(a, b: {t}): bool {{.borrow.}}",
    fmt"func `$`*(a: {t}): string {{.borrow.}}",
  ]
  if d.isFlags:
    let integer = spell(d.underlying)
    result.add @[
      fmt"func `or`*(a, b: {t}): {t} {{.borrow.}}",
      fmt"func `and`*(a, b: {t}): {t} {{.borrow.}}",
      fmt"func `not`*(a: {t}): {t} {{.borrow.}}",
      fmt"func contains*(a, b: {t}): bool =",
      "  ## True if every bit of `b` is set in `a`.",
      fmt"  ({integer}(a) and {integer}(b)) == {integer}(b)",
    ]

# ---------------------------------------------------------------------------
# modules
# ---------------------------------------------------------------------------

const
  structPragma = "{.pragma: mdtype, pure, bycopy, completeStruct.}"
  aliasPragma = "{.pragma: mdalias.}"
  interfacePragma = "{.pragma: mdinterface.}"
  vtablePragma = "{.pragma: mdvtbl, pure, inheritable.}"

func declarationsFile(k: Module): string =
  ## winrttypes or a namespace module. Parameterised interfaces come first,
  ## each beside its vtable: otherwise Nim 2.2 hits an internal error.
  let parameterised = k.declarations.filterIt(it.isParameterised)
  let others = k.declarations.filterIt(not it.isParameterised)
  let types =
    parameterised.mapIt(typeDeclaration(it) & vtableDeclaration(it)).concat &
    others.map(typeDeclaration).concat &
    others.filterIt(it.hasVtable).map(vtableDeclaration).concat
  let namespaces = k.namespaces.join(", ")
  let about =
    if k.namespaces.len > 1:
      fmt"the namespaces {namespaces} refer to each other in a cycle, and share this module"
    else:
      ""
  let pragmas =
    if k.kind == mkTypes:
      @[structPragma]
    else:
      @[structPragma, aliasPragma, interfacePragma, vtablePragma]
  let imports = k.imports.join(", ")
  fmt"""
{header(k.name, about)}
import ./[{imports}]
export {imports}
""" &
    paragraph(pragmas) & section("type", types) &
    section("const", k.declarations.map(constDeclarations).concat) &
    lines(k.declarations.map(enumFuncs).concat)

func shimFile(k: Module): string =
  ## A shim: re-exports the module its namespace shares.
  let (namespace, group) = (k.namespaces[0], k.imports[0])
  let about =
    fmt"{namespace} shares {group} with the namespaces it refers to in a cycle"
  fmt"""
{header(k.name, about)}
import ./{group}
export {group}
"""

func genericsFile(p: Plan): string =
  ## winrtgenerics: the instantiations' IIDs, sorted.
  let consts = p.instantiationIids.sortedByIt(it.name).mapIt(
      fmt"  {it.name}*: GUID = {nimLiteral(it.iid)}"
    )
  fmt"""
{header("winrtgenerics")}
import ./winrtbase
export winrtbase
""" &
    section("const", consts)

func moduleFile(k: Module): string =
  ## The source of module `k`.
  case k.kind
  of mkTypes, mkNamespace:
    declarationsFile(k)
  of mkShim:
    shimFile(k)

func renderModules*(p: Plan): seq[GenModule] =
  ## Every module's name and source.
  @[
    GenModule(name: "winrtbase", code: header("winrtbase") & "\n" & baseModule),
    GenModule(name: "winrtgenerics", code: genericsFile(p)),
  ] & p.modules.mapIt(GenModule(name: it.name, code: moduleFile(it)))
