# render.nim — renders the plan (winrt/plan) as the Nim source of the WinRT
# modules, from the plan alone. The plan has settled what each type is called, what it holds
# with every reference resolved, and which module declares it; this lays it
# out in Nim: the type sections with their enums, objects and vtables, then the
# consts, and the imports that tie the modules together.

import std/[algorithm, options, sequtils, strformat, strutils]
import ../[guid, generator]
import ./plan
{.push warning[UnusedImport]: off.}
from ./winrtbase import nil # compiled here too, so the compiler checks it
{.pop.}

const baseModule = staticRead("winrtbase.nim").replace("\r\n", "\n")
  ## winrtbase as it is written out.

func lines(xs: openArray[string]): string =
  ## `xs`, each followed by a newline.
  xs.mapIt(it & "\n").join

func paragraph(xs: seq[string]): string =
  ## `xs` after a blank line, each on a line of its own; nothing when there
  ## are none.
  if xs.len > 0:
    lines(@[""] & xs)
  else:
    ""

func section(keyword: string, xs: seq[string]): string =
  ## A `type` or `const` section of `xs` after a blank line; nothing when
  ## there are none (an empty section does not parse).
  if xs.len > 0:
    paragraph(@[keyword] & xs)
  else:
    ""

func header(name: string, about = ""): string =
  ## The first line of a module, its doc comment, and a second when there is
  ## more to say `about` it.
  let first =
    fmt"## generated by winmd2nim from WinRT metadata — {name} (do not edit)"
  if about.len > 0:
    first & "\n## " & about
  else:
    first

func spell(t: AbiType): string =
  ## How Nim writes `t`: `int32`, `ptr Uri`, `ptr IVector[HSTRING]`,
  ## `array[4, uint8]`; a pointer to nothing is a `pointer`.
  case t.kind
  of akVoid:
    "void"
  of akNamed:
    t.name
  of akPointer:
    if t.target.kind == akVoid:
      "pointer"
    else:
      "ptr " & spell(t.target)
  of akInstantiation:
    let args = t.args.map(spell).join(", ")
    fmt"{t.definition}[{args}]"
  of akArray:
    fmt"array[{t.count}, {spell(t.element)}]"

func hasVtable(d: Declaration): bool =
  ## An interface or delegate: a type with a vtable and an IID.
  d.kind in {dkInterface, dkDelegate}

func isParameterised(d: Declaration): bool =
  ## A parameterised interface or delegate, `IVector[T]`.
  d.hasVtable and d.genericParameters.len > 0

func generics(d: Declaration): string =
  ## The generic parameters of interface or delegate `d`, `[T]` or `[K, V]`;
  ## "" when it has none.
  if d.genericParameters.len > 0:
    let list = d.genericParameters.join(", ")
    fmt"[{list}]"
  else:
    ""

# ---------------------------------------------------------------------------
# declarations, each as the lines it takes in a type or const section
# ---------------------------------------------------------------------------

func slotType(s: VtableSlot): string =
  ## A vtable slot's type: the method as the ABI calls it; one the metadata
  ## cannot spell stays a `pointer`.
  if s.parameters.isNone:
    return "pointer # signature not mapped"
  let list = s.parameters.get.mapIt(fmt"{it.name}: {spell(it.ty)}").join(", ")
  fmt"proc({list}): HRESULT {{.stdcall.}}"

func typeDeclaration(d: Declaration): seq[string] =
  ## The declaration of `d` in a type section.
  case d.kind
  of dkEnum:
    # a distinct integer: its members are consts (constDeclarations), its
    # operations borrowed (enumFuncs)
    @[fmt"  {d.name}* = distinct {spell(d.underlying)}"]
  of dkStruct:
    @[fmt"  {d.name}* {{.mdtype.}} = object"] &
      d.fields.mapIt(fmt"    {it.name}*: {spell(it.ty)}")
  of dkInterface, dkDelegate:
    # the object behind a pointer to an interface or delegate
    @[
      fmt"  {d.name}*{generics(d)} {{.mdinterface.}} = object",
      fmt"    lpVtbl*: ptr {d.vtableName}{generics(d)}",
    ]
  of dkClass:
    if d.defaultInterface.isSome:
      # a runtime class: what crosses the ABI is its default interface
      @[fmt"  {d.name}* {{.mdalias.}} = {spell(d.defaultInterface.get)}"]
    else:
      # a static class: no default interface, and no instances
      @[fmt"  {d.name}* {{.mdinterface.}} = object", "    lpVtbl*: pointer"]

func vtableDeclaration(d: Declaration): seq[string] =
  ## The vtable of interface or delegate `d`: its base, then its methods in
  ## slot order.
  let parent = if d.kind == dkDelegate: "IUnknownVtbl" else: "IInspectableVtbl"
  @[fmt"  {d.vtableName}*{generics(d)} {{.mdvtbl.}} = object of {parent}"] &
    d.slots.mapIt(fmt"    {it.name}*: {slotType(it)}")

func constDeclarations(d: Declaration): seq[string] =
  ## The consts of `d`: the IID of an interface or delegate, the name of a
  ## runtime class, or the members of an enum.
  case d.kind
  of dkInterface, dkDelegate:
    @[fmt"  {d.iidName}*: GUID = {nimLiteral(d.guid)}"]
  of dkClass:
    @[fmt"  {d.classNameConst}*: string = {escape(d.className)}"]
  of dkEnum:
    d.members.mapIt(fmt"  {it.name}*: {d.name} = {d.name}({it.value})")
  of dkStruct:
    @[]

func enumFuncs(d: Declaration): seq[string] =
  ## What enum `d` borrows from its integer, after a blank line: comparing and
  ## printing, and for a [Flags] enum combining its members and testing for
  ## them (`NetworkTypes_Internet in types`); nothing for any other type.
  if d.kind != dkEnum:
    return
  let t = d.name
  result = @[
    "",
    fmt"func `==`*(a, b: {t}): bool {{.borrow.}}",
    fmt"func `$`*(a: {t}): string {{.borrow.}}",
  ]
  if d.isFlags:
    let integer = spell(d.underlying)
    result.add @[
      fmt"func `or`*(a, b: {t}): {t} {{.borrow.}}",
      fmt"func `and`*(a, b: {t}): {t} {{.borrow.}}",
      fmt"func `not`*(a: {t}): {t} {{.borrow.}}",
      fmt"func contains*(a, b: {t}): bool =",
      "  ## True if every bit of `b` is set in `a`.",
      fmt"  ({integer}(a) and {integer}(b)) == {integer}(b)",
    ]

# ---------------------------------------------------------------------------
# modules
# ---------------------------------------------------------------------------

const
  structPragma = "{.pragma: mdtype, pure, bycopy, completeStruct.}"
  aliasPragma = "{.pragma: mdalias.}"
  interfacePragma = "{.pragma: mdinterface.}"
  vtablePragma = "{.pragma: mdvtbl, pure, inheritable.}"

func declarationsFile(k: Module): string =
  ## winrttypes, or the module of a namespace (or of the namespaces of a
  ## cycle): its declarations in one type section, then their consts (IIDs,
  ## runtime class names, enum members), then what its enums borrow from
  ## their integers.
  ##
  ## The parameterised interfaces come first, each object followed by its
  ## vtable: instantiating `TypedEventHandler[A, B]` in a slot or a class
  ## alias before the vtable its body points to has been seen is an internal
  ## error in Nim 2.2.
  let parameterised = k.declarations.filterIt(it.isParameterised)
  let others = k.declarations.filterIt(not it.isParameterised)
  let types =
    parameterised.mapIt(typeDeclaration(it) & vtableDeclaration(it)).concat &
    others.map(typeDeclaration).concat &
    others.filterIt(it.hasVtable).map(vtableDeclaration).concat
  let namespaces = k.namespaces.join(", ")
  let about =
    if k.namespaces.len > 1:
      fmt"the namespaces {namespaces} refer to each other in a cycle, and share this module"
    else:
      ""
  let pragmas =
    if k.kind == mkTypes: # enums and structs only
      @[structPragma]
    else:
      @[structPragma, aliasPragma, interfacePragma, vtablePragma]
  let imports = k.imports.join(", ")
  fmt"""
{header(k.name, about)}
import ./[{imports}]
export {imports}
""" &
    paragraph(pragmas) & section("type", types) &
    section("const", k.declarations.map(constDeclarations).concat) &
    lines(k.declarations.map(enumFuncs).concat)

func shimFile(k: Module): string =
  ## A namespace of a cycle: re-exports the module it shares with the others.
  let (namespace, group) = (k.namespaces[0], k.imports[0])
  let about =
    fmt"{namespace} shares {group} with the namespaces it refers to in a cycle"
  fmt"""
{header(k.name, about)}
import ./{group}
export {group}
"""

func genericsFile(p: Plan): string =
  ## winrtgenerics: the IID of every instantiation the metadata uses, sorted
  ## by name.
  let consts = p.instantiationIids.sortedByIt(it.name).mapIt(
      fmt"  {it.name}*: GUID = {nimLiteral(it.iid)}"
    )
  fmt"""
{header("winrtgenerics")}
import ./winrtbase
export winrtbase
""" &
    section("const", consts)

func moduleFile(k: Module): string =
  ## Module `k` as it is written out.
  case k.kind
  of mkTypes, mkNamespace:
    declarationsFile(k)
  of mkShim:
    shimFile(k)

func renderModules*(p: Plan): seq[GenModule] =
  ## Every module to write out, each its name (the `.nim` file's, without the
  ## extension) and its Nim source: winrtbase, winrtgenerics, then the modules
  ## of the plan.
  @[
    GenModule(name: "winrtbase", code: header("winrtbase") & "\n" & baseModule),
    GenModule(name: "winrtgenerics", code: genericsFile(p)),
  ] & p.modules.mapIt(GenModule(name: it.name, code: moduleFile(it)))
