# test_winrt_render.nim — the WinRT modules rendered from a plan built by
# hand rather than read from metadata: how each kind of declaration and module
# is laid out (doAssert-based).
# Run: nim r --verbosity:0 tests/test_winrt_render.nim  (or `nimble test`)

import std/[options, sequtils, strutils, tables]
import ../src/winmd/[guid, generator]
import ../src/winmd/winrt/[plan, render]

func named(name: string): AbiType =
  AbiType(kind: akNamed, name: name)

func pointerTo(target: AbiType): AbiType =
  AbiType(kind: akPointer, target: target)

func slot(name: string, parameters: varargs[Parameter]): VtableSlot =
  VtableSlot(name: name, parameters: some(@parameters))

let
  status = Declaration(
    kind: dkEnum,
    name: "AsyncStatus",
    underlying: named("int32"),
    isFlags: false,
    members: @[
      (name: "AsyncStatus_Started", value: "0'i32"),
      (name: "AsyncStatus_Completed", value: "1'i32"),
    ],
  )
  attributes = Declaration(
    kind: dkEnum,
    name: "FileAttributes",
    underlying: named("uint32"),
    isFlags: true,
    members: @[(name: "FileAttributes_ReadOnly", value: "1'u32")],
  )
  sample = Declaration(
    kind: dkStruct,
    name: "Sample",
    fields: @[
      (name: "Bytes", ty: AbiType(kind: akArray, element: named("uint8"), count: 4)),
      (name: "Context", ty: pointerTo(AbiType(kind: akVoid))),
    ],
  )
  vector = Declaration(
    kind: dkInterface,
    name: "IVector",
    genericParameters: @["T"],
    vtableName: "IVectorVtbl",
    iidName: "IID_IVector",
    guid: parseGuid("913337e9-11a1-4345-a3a2-4e7f956e222d"),
    slots: @[
      slot(
        "GetAt",
        (
          name: "this",
          ty: pointerTo(
            AbiType(kind: akInstantiation, definition: "IVector", args: @[named("T")])
          ),
        ),
        (name: "index", ty: named("uint32")),
        (name: "retval", ty: pointerTo(named("T"))),
      )
    ],
  )
  stringable = Declaration(
    kind: dkInterface,
    name: "IStringable",
    vtableName: "IStringableVtbl",
    iidName: "IID_IStringable",
    guid: parseGuid("96369f54-8eb6-48f0-abce-c1b211e627c3"),
    slots: @[
      slot(
        "ToString",
        (name: "this", ty: pointerTo(named("IStringable"))),
        (name: "retval", ty: pointerTo(named("HSTRING"))),
      ),
      VtableSlot(name: "Unspellable", parameters: none(seq[Parameter])),
    ],
  )
  handler = Declaration(
    kind: dkDelegate,
    name: "AsyncActionCompletedHandler",
    vtableName: "AsyncActionCompletedHandlerVtbl",
    iidName: "IID_AsyncActionCompletedHandler",
    guid: parseGuid("a4ed5c81-76c9-40bd-8be6-b1d90fb20ae7"),
    slots: @[
      slot(
        "Invoke",
        (name: "this", ty: pointerTo(named("AsyncActionCompletedHandler"))),
        (name: "asyncStatus", ty: named("AsyncStatus")),
      )
    ],
  )
  uri = Declaration(
    kind: dkClass,
    name: "Uri",
    className: "Windows.Foundation.Uri",
    classNameConst: "RuntimeClass_Windows_Foundation_Uri",
    defaultInterface: some(named("IUriRuntimeClass")),
  )
  launcher = Declaration(
    kind: dkClass,
    name: "Launcher",
    className: "Windows.System.Launcher",
    classNameConst: "RuntimeClass_Windows_System_Launcher",
    defaultInterface: none(AbiType),
  )

let handBuilt = Plan(
  modules: @[
    Module(
      kind: mkTypes,
      name: "winrttypes",
      imports: @["winrtbase"],
      declarations: @[status, attributes, sample],
    ),
    Module(
      kind: mkNamespace,
      name: "foundation_group",
      namespaces: @["Windows.Foundation", "Windows.System"],
      imports: @["winrtbase", "winrttypes"],
      declarations: @[stringable, vector, handler, uri, launcher],
    ),
    Module(
      kind: mkShim,
      name: "system",
      namespaces: @["Windows.System"],
      imports: @["foundation_group"],
    ),
  ],
  instantiationIids: @[
    (
      name: "IID_IVector_HSTRING",
      iid: parseGuid("98b9acc1-4b56-532e-ac73-03d5291cca90"),
    ),
    (
      name: "IID_IAsyncOperation_bool",
      iid: parseGuid("cdb5efb3-5788-509d-9be1-71ccb8a3362a"),
    ),
  ],
)

let modules = renderModules(handBuilt)
doAssert modules.mapIt(it.name) ==
  @["winrtbase", "winrtgenerics", "winrttypes", "foundation_group", "system"]
let code = modules.mapIt((it.name, it.code)).toTable

# winrtbase is written out as it is, after the header
doAssert code["winrtbase"].startsWith(
  "## generated by winmd2nim from WinRT metadata — winrtbase (do not edit)\n## What every"
)

# an enum is a distinct integer, its members consts, with what it borrows
# from its integer after them (a [Flags] one more)
doAssert code["winrttypes"] == """
## generated by winmd2nim from WinRT metadata — winrttypes (do not edit)
import ./[winrtbase]
export winrtbase

{.pragma: mdtype, pure, bycopy, completeStruct.}

type
  AsyncStatus* = distinct int32
  FileAttributes* = distinct uint32
  Sample* {.mdtype.} = object
    Bytes*: array[4, uint8]
    Context*: pointer

const
  AsyncStatus_Started*: AsyncStatus = AsyncStatus(0'i32)
  AsyncStatus_Completed*: AsyncStatus = AsyncStatus(1'i32)
  FileAttributes_ReadOnly*: FileAttributes = FileAttributes(1'u32)

func `==`*(a, b: AsyncStatus): bool {.borrow.}
func `$`*(a: AsyncStatus): string {.borrow.}

func `==`*(a, b: FileAttributes): bool {.borrow.}
func `$`*(a: FileAttributes): string {.borrow.}
func `or`*(a, b: FileAttributes): FileAttributes {.borrow.}
func `and`*(a, b: FileAttributes): FileAttributes {.borrow.}
func `not`*(a: FileAttributes): FileAttributes {.borrow.}
func contains*(a, b: FileAttributes): bool =
  ## True if every bit of `b` is set in `a`.
  (uint32(a) and uint32(b)) == uint32(b)
"""

# the parameterised interfaces first, each beside its vtable, then the other
# declarations, then their vtables; a delegate's vtable extends IUnknown's
doAssert code["foundation_group"] == """
## generated by winmd2nim from WinRT metadata — foundation_group (do not edit)
## the namespaces Windows.Foundation, Windows.System refer to each other in a cycle, and share this module
import ./[winrtbase, winrttypes]
export winrtbase, winrttypes

{.pragma: mdtype, pure, bycopy, completeStruct.}
{.pragma: mdalias.}
{.pragma: mdinterface.}
{.pragma: mdvtbl, pure, inheritable.}

type
  IVector*[T] {.mdinterface.} = object
    lpVtbl*: ptr IVectorVtbl[T]
  IVectorVtbl*[T] {.mdvtbl.} = object of IInspectableVtbl
    GetAt*: proc(this: ptr IVector[T], index: uint32, retval: ptr T): HRESULT {.stdcall.}
  IStringable* {.mdinterface.} = object
    lpVtbl*: ptr IStringableVtbl
  AsyncActionCompletedHandler* {.mdinterface.} = object
    lpVtbl*: ptr AsyncActionCompletedHandlerVtbl
  Uri* {.mdalias.} = IUriRuntimeClass
  Launcher* {.mdinterface.} = object
    lpVtbl*: pointer
  IStringableVtbl* {.mdvtbl.} = object of IInspectableVtbl
    ToString*: proc(this: ptr IStringable, retval: ptr HSTRING): HRESULT {.stdcall.}
    Unspellable*: pointer # signature not mapped
  AsyncActionCompletedHandlerVtbl* {.mdvtbl.} = object of IUnknownVtbl
    Invoke*: proc(this: ptr AsyncActionCompletedHandler, asyncStatus: AsyncStatus): HRESULT {.stdcall.}

const
  IID_IStringable*: GUID = guid"96369f54-8eb6-48f0-abce-c1b211e627c3"
  IID_IVector*: GUID = guid"913337e9-11a1-4345-a3a2-4e7f956e222d"
  IID_AsyncActionCompletedHandler*: GUID = guid"a4ed5c81-76c9-40bd-8be6-b1d90fb20ae7"
  RuntimeClass_Windows_Foundation_Uri*: string = "Windows.Foundation.Uri"
  RuntimeClass_Windows_System_Launcher*: string = "Windows.System.Launcher"
"""

doAssert code["system"] == """
## generated by winmd2nim from WinRT metadata — system (do not edit)
## Windows.System shares foundation_group with the namespaces it refers to in a cycle
import ./foundation_group
export foundation_group
"""

# the instantiations' IIDs, sorted by name
doAssert code["winrtgenerics"] == """
## generated by winmd2nim from WinRT metadata — winrtgenerics (do not edit)
import ./winrtbase
export winrtbase

const
  IID_IAsyncOperation_bool*: GUID = guid"cdb5efb3-5788-509d-9be1-71ccb8a3362a"
  IID_IVector_HSTRING*: GUID = guid"98b9acc1-4b56-532e-ac73-03d5291cca90"
"""

# a module with nothing to declare has no sections: an empty one does not
# parse (metadata with no enums and no structs)
let empty = Module(kind: mkTypes, name: "winrttypes", imports: @["winrtbase"])
doAssert renderModules(Plan(modules: @[empty]))[2].code == """
## generated by winmd2nim from WinRT metadata — winrttypes (do not edit)
import ./[winrtbase]
export winrtbase

{.pragma: mdtype, pure, bycopy, completeStruct.}
"""

echo "test_winrt_render: all assertions passed"
